import mallou from './mallou.svg';
import chao from './chao.svg';

export const options = [
  { name: 'Ver todas', identificate: 'todas' },
  { name: 'Pasodobles', identificate: 'pasodoble' },
  { name: 'Muiñeiras', identificate: 'muiñeira' },
  { name: 'Xotas', identificate: 'xota' },
  { name: 'Rumbas', identificate: 'rumba' },
  { name: 'Foliadas', identificate: 'foliada' },
  { name: 'Vals', identificate: 'vals' },
];

export const songsList = [
  {
    id: 1,
    name: 'P. Mallou',
    sheet: mallou,
    sheetDrum: chao,
    type: 'pasodoble',
  },
  {
    id: 2,
    name: 'M. do Chao',
    sheet: chao,
    sheetDrum: mallou,
    type: 'muiñeira',
  },
  {
    id: 3,
    name: 'P. Berbés',
    sheet: mallou,
    sheetDrum: chao,
    type: 'pasodoble',
  },
  {
    id: 4,
    name: 'M. Lagares',
    sheet: mallou,
    sheetDrum: chao,
    type: 'muiñeira',
  },
  {
    id: 5,
    name: 'X. Poleiro',
    sheet: null,
    sheetDrum: chao,
    type: 'xota',
  },
  {
    id: 6,
    name: 'P. Trabazos',
    sheet: null,
    sheetDrum: chao,
    type: 'pasodoble',
  },
  {
    id: 7,
    name: 'P. Arnoia',
    sheet: null,
    sheetDrum: chao,
    type: 'pasodoble',
  },
  {
    id: 8,
    name: 'V. Muradelle',
    sheet: mallou,
    sheetDrum: null,
    type: 'vals',
  },
  {
    id: 9,
    name: 'R. Carnaval de Vilariño',
    sheet: mallou,
    sheetDrum: null,
    type: 'rumba',
  },
  {
    id: 10,
    name: 'F. Angoares',
    sheet: mallou,
    sheetDrum: null,
    type: 'foliada',
  },
  {
    id: 11,
    name: 'M. Loliña',
    sheet: mallou,
    sheetDrum: chao,
    type: 'muiñeira',
  },
  {
    id: 12,
    name: 'X. Santiago',
    sheet: mallou,
    sheetDrum: chao,
    type: 'xota',
  },
  {
    id: 13,
    name: 'X. de Lugo',
    sheet: mallou,
    sheetDrum: chao,
    type: 'xota',
  },
  {
    id: 14,
    name: 'P. Sobrado dos Monxes',
    sheet: mallou,
    sheetDrum: chao,
    type: 'pasodoble',
  },
  {
    id: 15,
    name: 'M. A grelada',
    sheet: mallou,
    sheetDrum: chao,
    type: 'muiñeira',
  },
  {
    id: 16,
    name: 'M. Areal',
    sheet: mallou,
    sheetDrum: chao,
    type: 'muiñeira',
  },
  {
    id: 17,
    name: 'P. San Roque',
    sheet: mallou,
    sheetDrum: chao,
    type: 'pasodoble',
  },
  {
    id: 18,
    name: 'M. Camposa',
    sheet: mallou,
    sheetDrum: chao,
    type: 'muiñeira',
  },
  {
    id: 19,
    name: 'F. dos Morenos',
    sheet: mallou,
    sheetDrum: chao,
    type: 'foliada',
  },
  {
    id: 20,
    name: 'P. do Condado',
    sheet: mallou,
    sheetDrum: chao,
    type: 'pasodoble',
  },
  {
    id: 21,
    name: 'M. Armenteira',
    sheet: mallou,
    sheetDrum: chao,
    type: 'muiñeira',
  },
  {
    id: 22,
    name: 'R. Carcacía',
    sheet: mallou,
    sheetDrum: chao,
    type: 'rumba',
  },
  {
    id: 23,
    name: 'R. de Vergara',
    sheet: mallou,
    sheetDrum: chao,
    type: 'rumba',
  },
];
